import { CarmaThemeType, FontColor } from "./types";
import { CarmaThemeColorPalette } from "./ColorPalettes/CarmaThemeColorPalette";

const {
  // blueLightest,
  blueLight,
  blueLightMedium,
  blueMedium,
  blueMediumDark,
  blueDark,
  blueDarkest,
  yellow,
  neutralLightest,
  neutralDark,
  neutralMedium,
  neutralLight,
  white,
  black,
  orange,
  orangeLight,
  red,
  green,
  greenLightest,
  greenLight,
  skyBlueLight,
  skyBlueMedium,
  purpleLight,
  pinkMediumDark,
  pinkMedium,
  shadow,
  transparent,
} = CarmaThemeColorPalette;

const fontColors: FontColor = {
  light: neutralMedium,
  medium: neutralDark,
  dark: blueDark,
  darkest: blueDarkest,
  highlight: blueLight,
  white: white,
  success: green,
  warning: yellow,
  error: red,
};

export const CarmaTheme: CarmaThemeType = {
  color: {
    callToAction: blueLight,
    callToActionInteractive: blueLightMedium,
    primary: blueMedium,
    primaryInteractive: blueMediumDark,
    background: neutralLightest,
    foreground: white,
    font: fontColors,
    success: green,
    warning: yellow,
    warningElevated: orange,
    error: red,
    white: white,
    black: black,
    border: neutralLight,
    shadow: shadow,
    transparent: transparent,
    team: {
      tnr: red,
      underwriting: orangeLight,
      wholesale: greenLightest,
      fieldAdvocate: greenLight,
      insideAdvocate: skyBlueLight,
      pdi: skyBlueMedium,
      transport: purpleLight,
      executiveResolution: pinkMediumDark,
      postOps: pinkMedium,
    },
  },
  border: `1px solid ${neutralLight}`,
  borderRadius: 3,
  boxShadow: `0 4px 7px ${shadow}`,
  boxShadowDeeper: `0 0px 24px ${shadow}`,
  font: {
    family: `'Brandon Text', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'`,
    size: {
      small: 10,
      normal: 12,
      medium: 16,
      large: 18,
      xlarge: 20,
      xxlarge: 24,
    },
    weight: {
      extraLight: 200,
      light: 300,
      normal: 400,
      medium: 500,
      bold: 700,
      black: 900,
    },
    color: fontColors,
  },
  spacing: {
    xxsmall: 4,
    xsmall: 8,
    small: 10,
    normal: 12,
    medium: 16,
    large: 20,
    xlarge: 24,
    xxlarge: 48,
  },
};
